version: '3'
services:
  db:
    image: postgres:13.3
    container_name: market_place_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 77girado
      TZ: "Asia/Tashkent"  # Установка временной зоны для PostgreSQL
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8008:8000
    depends_on:
      - db
    volumes:
      - media-volume:/code/media/  # Ваш том (volume) для media
      # ... Другие объявленные volumes ...

  pgadmin:
    container_name: pgadmin_marketplace
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=marketplace@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=eshonpir63
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  pgdata:  # Том для PostgreSQL
  media-volume:  # Ваш том (volume) для media
