version: '3'
services:
  db:
    image: postgres:13.3
    container_name: market_place_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 77girado
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8008:8000
    depends_on:
      - db

  pgadmin:
    container_name: pgadmin_marketplace
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=marketplace@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=eshonpir63
    ports:
      - "8080:80"  # Здесь изменяем порт
    depends_on:
      - db

volumes:
  pgdata: