from repositories.base import BaseRepository
from fastapi_pagination import Params as Pagination, Page, paginate
from repositories.users import UsersRepository
from repositories.roles import RolesRepository
from repositories.user_employees import UserEmployeesRepository
from repositories.emails import EmailsRepository
from repositories.currencies import CurrenciesRepository
from repositories.activities import ActivitiesRepository
from repositories.languages import LanguagesRepository
from repositories.accommodations import AccommodationsRepository
from repositories.categories import CategoriesRepository
from repositories.types import TypesRepository
from repositories.countries import CountriesRepository
from repositories.regions import RegionsRepository

from repositories.tour_statuses import TourStatusesRepository
from repositories.tour_children_ages import TourChildrenAgesRepository
from repositories.tour_activity_levels import TourActivityLevelsRepository
from repositories.tours import ToursRepository
from repositories.tour_media_group import TourMediaGroupRepository
# from repositories.tour_categories import TourCategoriesRepository
# from repositories.tour_additional_types import TourAdditionalTypesRepository
from repositories.tour_languages import TourLanguagesRepository
from repositories.tour_activities import TourActivitiesRepository
from repositories.tour_accommodations import TourAccommodationsRepository
from repositories.tour_countries import TourCountriesRepository
from repositories.tour_regions import TourRegionsRepository
from repositories.tour_prices import TourPricesRepository
from repositories.tour_days import TourDaysRepository, TourDayMediaGroupsRepository
from repositories.tour_hotels import TourHotelsRepository, TourHotelMediaGroupsRepository



from repositories.tour_comments import TourCommentsRepository, TourCommentsMediaRepository


from repositories.blogs import BlogsRepository, BlogMediaRepository
from repositories.blog_countries import BlogCountriesRepository

from repositories.support_questions import SupportQuestionsRepository, QuestionDocsRepository

from repositories.sold_tours import SoldToursRepository

from repositories.statistics_of_views import StatisticsOfViewsRepository
# from repositories.tourprices import TourPricesRepository
# from repositories.tour_activities import TourActivitiesRepository
# from repositories.favorite_tours import FavoriteToursRepository
# from repositories.tour_comments import TourCommentsRepository
# from repositories.tour_comments_media import TourCommentsMediaRepository
# from repositories.tour_languages import TourLanguagesRepository