"""favorites

Revision ID: 0316069f67a0
Revises: e5143661297e
Create Date: 2023-08-26 14:12:16.322085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0316069f67a0'
down_revision: Union[str, None] = 'e5143661297e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_tours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tour_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorite_tours_id'), 'favorite_tours', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorite_tours_id'), table_name='favorite_tours')
    op.drop_table('favorite_tours')
    # ### end Alembic commands ###
