"""3

Revision ID: 04ab484ad6e7
Revises: f2842bca1c18
Create Date: 2023-08-14 14:46:56.879327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ab484ad6e7'
down_revision: Union[str, None] = 'f2842bca1c18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('traveler_managers', 'traveler_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('traveler_managers', 'manager_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_traveler_managers_id', table_name='traveler_managers')
    op.drop_column('traveler_managers', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traveler_managers', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_traveler_managers_id', 'traveler_managers', ['id'], unique=False)
    op.alter_column('traveler_managers', 'manager_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('traveler_managers', 'traveler_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
