"""short_description for hotels

Revision ID: 15d48fd6d4e2
Revises: 96ba06cce3fd
Create Date: 2023-10-13 11:01:10.814458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15d48fd6d4e2'
down_revision: Union[str, None] = '96ba06cce3fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_hotels', sa.Column('short_description', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tour_hotels', sa.Column('stars', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_hotels', 'stars')
    op.drop_column('tour_hotels', 'short_description')
    # ### end Alembic commands ###
