"""includes and excludes in price

Revision ID: 17aa38bcdb9d
Revises: 42f760425de1
Create Date: 2023-10-18 17:06:27.199035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17aa38bcdb9d'
down_revision: Union[str, None] = '42f760425de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excludes_in_price',
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excludes_in_price_id'), 'excludes_in_price', ['id'], unique=False)
    op.create_table('includes_in_price',
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_includes_in_price_id'), 'includes_in_price', ['id'], unique=False)
    op.drop_column('tours', 'not_included_in_price')
    op.drop_column('tours', 'included_in_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('included_in_price', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('tours', sa.Column('not_included_in_price', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_includes_in_price_id'), table_name='includes_in_price')
    op.drop_table('includes_in_price')
    op.drop_index(op.f('ix_excludes_in_price_id'), table_name='excludes_in_price')
    op.drop_table('excludes_in_price')
    # ### end Alembic commands ###
