"""tour accommodations

Revision ID: 1e36d94d8ad2
Revises: 43e9e2d2db63
Create Date: 2023-10-13 17:58:00.806159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e36d94d8ad2'
down_revision: Union[str, None] = '43e9e2d2db63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
