"""updated_tours

Revision ID: 20d278875849
Revises: 834c596b488d
Create Date: 2023-10-08 01:21:09.520764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d278875849'
down_revision: Union[str, None] = '834c596b488d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tour_categories_id', table_name='tour_categories')
    op.drop_table('tour_categories')
    op.drop_index('ix_tour_additional_types_id', table_name='tour_additional_types')
    op.drop_table('tour_additional_types')
    op.add_column('tours', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tours', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tours', type_='foreignkey')
    op.drop_column('tours', 'category_id')
    op.create_table('tour_additional_types',
    sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tour_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], name='tour_additional_types_tour_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], name='tour_additional_types_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tour_additional_types_pkey')
    )
    op.create_index('ix_tour_additional_types_id', 'tour_additional_types', ['id'], unique=False)
    op.create_table('tour_categories',
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tour_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='tour_categories_category_id_fkey'),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], name='tour_categories_tour_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='tour_categories_pkey')
    )
    op.create_index('ix_tour_categories_id', 'tour_categories', ['id'], unique=False)
    # ### end Alembic commands ###
