"""hotel types

Revision ID: 21cc124c2c23
Revises: 1c779225ef20
Create Date: 2023-10-13 11:37:51.572502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21cc124c2c23'
down_revision: Union[str, None] = '1c779225ef20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_hotel_types',
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_hotel_types_id'), 'tour_hotel_types', ['id'], unique=False)
    op.add_column('tour_hotels', sa.Column('hotel_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tour_hotels', 'tour_hotel_types', ['hotel_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tour_hotels', type_='foreignkey')
    op.drop_column('tour_hotels', 'hotel_type_id')
    op.drop_index(op.f('ix_tour_hotel_types_id'), table_name='tour_hotel_types')
    op.drop_table('tour_hotel_types')
    # ### end Alembic commands ###
