"""country

Revision ID: 238d8c29d63c
Revises: 4f958983c29a
Create Date: 2023-09-04 14:19:21.528510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '238d8c29d63c'
down_revision: Union[str, None] = '4f958983c29a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('country', sa.String(), nullable=False))
    op.alter_column('tours', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tours', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('tours', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tours', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('tours', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('tours', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('tours', 'country')
    # ### end Alembic commands ###
