"""tour days

Revision ID: 313c241cf39e
Revises: dfc42a863cce
Create Date: 2023-10-11 16:35:29.540936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '313c241cf39e'
down_revision: Union[str, None] = 'dfc42a863cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_day_media_groups',
    sa.Column('tour_day_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tour_day_id'], ['tour_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_day_media_groups_id'), 'tour_day_media_groups', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tour_day_media_groups_id'), table_name='tour_day_media_groups')
    op.drop_table('tour_day_media_groups')
    # ### end Alembic commands ###
