"""photos

Revision ID: 363831e0c7a2
Revises: 9c8dd6ce66f2
Create Date: 2023-08-28 12:36:42.910385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '363831e0c7a2'
down_revision: Union[str, None] = '9c8dd6ce66f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_comments_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_comment_id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tour_comment_id'], ['tour_comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tour_comments_photos')
    # ### end Alembic commands ###
