"""dates_tours

Revision ID: 377cef5f1c98
Revises: dbd08fd39e0a
Create Date: 2023-09-04 11:48:23.769684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '377cef5f1c98'
down_revision: Union[str, None] = 'dbd08fd39e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('tours', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tours', 'end_date')
    op.drop_column('tours', 'start_date')
    # ### end Alembic commands ###
