"""forms

Revision ID: 4c11ecfc1355
Revises: 71b04c614651
Create Date: 2023-10-16 21:11:20.077023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c11ecfc1355'
down_revision: Union[str, None] = '71b04c614651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_forms',
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('dates', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('price_per_participant', sa.Float(), nullable=False),
    sa.Column('amount_of_participants', sa.Integer(), nullable=False),
    sa.Column('average_age', sa.Float(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_forms_id'), 'application_forms', ['id'], unique=False)
    op.create_table('ask_question_forms',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ask_question_forms_id'), 'ask_question_forms', ['id'], unique=False)
    op.create_table('call_back_forms',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_back_forms_id'), 'call_back_forms', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_back_forms_id'), table_name='call_back_forms')
    op.drop_table('call_back_forms')
    op.drop_index(op.f('ix_ask_question_forms_id'), table_name='ask_question_forms')
    op.drop_table('ask_question_forms')
    op.drop_index(op.f('ix_application_forms_id'), table_name='application_forms')
    op.drop_table('application_forms')
    # ### end Alembic commands ###
