"""travelermanagers

Revision ID: 4f2c69cfa566
Revises: b457af4ae3e5
Create Date: 2023-08-14 17:36:39.135768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f2c69cfa566'
down_revision: Union[str, None] = 'b457af4ae3e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travelers_managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('traveler_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['traveler_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travelers_managers_id'), 'travelers_managers', ['id'], unique=False)
    op.create_index(op.f('ix_travelers_managers_manager_id'), 'travelers_managers', ['manager_id'], unique=False)
    op.create_index(op.f('ix_travelers_managers_traveler_id'), 'travelers_managers', ['traveler_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_travelers_managers_traveler_id'), table_name='travelers_managers')
    op.drop_index(op.f('ix_travelers_managers_manager_id'), table_name='travelers_managers')
    op.drop_index(op.f('ix_travelers_managers_id'), table_name='travelers_managers')
    op.drop_table('travelers_managers')
    # ### end Alembic commands ###
