"""link about

Revision ID: 4f958983c29a
Revises: 377cef5f1c98
Create Date: 2023-09-04 12:17:49.552115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f958983c29a'
down_revision: Union[str, None] = '377cef5f1c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('link', sa.String(), nullable=True))
    op.add_column('users', sa.Column('about', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about')
    op.drop_column('users', 'link')
    # ### end Alembic commands ###
