"""title

Revision ID: 5bbbb5224f30
Revises: 0316069f67a0
Create Date: 2023-08-27 10:47:00.301572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bbbb5224f30'
down_revision: Union[str, None] = '0316069f67a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('tours', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tours', 'title')
    # ### end Alembic commands ###
