"""support questions

Revision ID: 6847585a0409
Revises: 88985ac20cce
Create Date: 2023-10-05 10:52:36.343778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6847585a0409'
down_revision: Union[str, None] = '88985ac20cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_questions',
    sa.Column('question', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_questions_id'), 'support_questions', ['id'], unique=False)
    op.create_table('question_docs',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['support_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_docs_id'), 'question_docs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_docs_id'), table_name='question_docs')
    op.drop_table('question_docs')
    op.drop_index(op.f('ix_support_questions_id'), table_name='support_questions')
    op.drop_table('support_questions')
    # ### end Alembic commands ###
