"""changes

Revision ID: 72cafbebe48a
Revises: c55dae98b5c7
Create Date: 2023-10-26 17:31:55.348765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72cafbebe48a'
down_revision: Union[str, None] = 'c55dae98b5c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_employees', sa.Column('travel_expert_id', sa.Integer(), nullable=False))
    op.drop_constraint('user_employees_user_id_fkey', 'user_employees', type_='foreignkey')
    op.create_foreign_key(None, 'user_employees', 'users', ['travel_expert_id'], ['id'])
    op.drop_column('user_employees', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_employees', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_employees', type_='foreignkey')
    op.create_foreign_key('user_employees_user_id_fkey', 'user_employees', 'users', ['user_id'], ['id'])
    op.drop_column('user_employees', 'travel_expert_id')
    # ### end Alembic commands ###
