"""views

Revision ID: 746b9d1646d2
Revises: b9436331571b
Create Date: 2023-09-04 14:55:23.006659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '746b9d1646d2'
down_revision: Union[str, None] = 'b9436331571b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('total_places', sa.Integer(), nullable=False))
    op.add_column('tours', sa.Column('free_places', sa.Integer(), nullable=False))
    op.add_column('tours', sa.Column('view_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tours', 'view_count')
    op.drop_column('tours', 'free_places')
    op.drop_column('tours', 'total_places')
    # ### end Alembic commands ###
