"""statuses2

Revision ID: 7b29b101c06b
Revises: b620b6b93d18
Create Date: 2023-08-26 00:33:54.111631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b29b101c06b'
down_revision: Union[str, None] = 'b620b6b93d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tour_statuses_tour_id_fkey', 'tour_statuses', type_='foreignkey')
    op.drop_column('tour_statuses', 'tour_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_statuses', sa.Column('tour_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tour_statuses_tour_id_fkey', 'tour_statuses', 'tours', ['tour_id'], ['id'])
    # ### end Alembic commands ###
