"""mediacom

Revision ID: 7c52ac7a100b
Revises: 363831e0c7a2
Create Date: 2023-08-28 13:55:59.745982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c52ac7a100b'
down_revision: Union[str, None] = '363831e0c7a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_comments_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_comment_id', sa.Integer(), nullable=False),
    sa.Column('media_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tour_comment_id'], ['tour_comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tour_comments_photos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_comments_photos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tour_comment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tour_comment_id'], ['tour_comments.id'], name='tour_comments_photos_tour_comment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tour_comments_photos_pkey')
    )
    op.drop_table('tour_comments_media')
    # ### end Alembic commands ###
