"""stats

Revision ID: 834c596b488d
Revises: adc52a67ae95
Create Date: 2023-10-08 00:28:16.020583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '834c596b488d'
down_revision: Union[str, None] = 'adc52a67ae95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics_of_views',
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('views', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistics_of_views_id'), 'statistics_of_views', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistics_of_views_id'), table_name='statistics_of_views')
    op.drop_table('statistics_of_views')
    # ### end Alembic commands ###
