"""tours_columns

Revision ID: 8dab97fd0f6c
Revises: f76751ec6ac2
Create Date: 2023-09-05 12:27:21.889515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dab97fd0f6c'
down_revision: Union[str, None] = 'f76751ec6ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('age_group', sa.String(), nullable=False))
    op.add_column('tours', sa.Column('children_age', sa.String(), nullable=False))
    op.add_column('tours', sa.Column('level_of_activity', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tours', 'level_of_activity')
    op.drop_column('tours', 'children_age')
    op.drop_column('tours', 'age_group')
    # ### end Alembic commands ###
