"""countries

Revision ID: 8f237bd2611d
Revises: 6847585a0409
Create Date: 2023-10-05 11:18:57.905970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f237bd2611d'
down_revision: Union[str, None] = '6847585a0409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('title', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('countries', sa.Column('meta_description', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('countries', sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('countries', sa.Column('filename', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'filename')
    op.drop_column('countries', 'description')
    op.drop_column('countries', 'meta_description')
    op.drop_column('countries', 'title')
    # ### end Alembic commands ###
