"""tour hotels

Revision ID: 96ba06cce3fd
Revises: 313c241cf39e
Create Date: 2023-10-11 17:18:51.881533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96ba06cce3fd'
down_revision: Union[str, None] = '313c241cf39e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_hotels',
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_hotels_id'), 'tour_hotels', ['id'], unique=False)
    op.create_table('tour_hotel_media_groups',
    sa.Column('tour_hotel_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tour_hotel_id'], ['tour_hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_hotel_media_groups_id'), 'tour_hotel_media_groups', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tour_hotel_media_groups_id'), table_name='tour_hotel_media_groups')
    op.drop_table('tour_hotel_media_groups')
    op.drop_index(op.f('ix_tour_hotels_id'), table_name='tour_hotels')
    op.drop_table('tour_hotels')
    # ### end Alembic commands ###
