"""users_role

Revision ID: 9bb3ee82413f
Revises: cf1ca697f0fd
Create Date: 2023-09-07 13:17:23.186625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bb3ee82413f'
down_revision: Union[str, None] = 'cf1ca697f0fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_traveler_expert')
    op.drop_column('users', 'is_traveler')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_traveler', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_traveler_expert', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
