"""users_id_tour

Revision ID: 9c8dd6ce66f2
Revises: a4fa914f517b
Create Date: 2023-08-27 16:58:13.603920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c8dd6ce66f2'
down_revision: Union[str, None] = 'a4fa914f517b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tours', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tours', type_='foreignkey')
    op.drop_column('tours', 'user_id')
    # ### end Alembic commands ###
