"""views3

Revision ID: 9dac530e6b60
Revises: 147625a1a991
Create Date: 2023-09-04 23:51:09.654078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dac530e6b60'
down_revision: Union[str, None] = '147625a1a991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tours', 'view_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('view_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
