"""prices10

Revision ID: a0ba9c01cd39
Revises: 751860d249ab
Create Date: 2023-09-07 12:16:53.593861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0ba9c01cd39'
down_revision: Union[str, None] = '751860d249ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_prices', 'new_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_prices', sa.Column('new_price', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
