"""changes

Revision ID: a737dc209760
Revises: 9fdb08fae339
Create Date: 2023-10-26 22:24:49.961525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a737dc209760'
down_revision: Union[str, None] = '9fdb08fae339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currencies', 'name')
    # ### end Alembic commands ###
