"""soldtours

Revision ID: adc52a67ae95
Revises: d96e0fff44bf
Create Date: 2023-10-07 00:38:07.211951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc52a67ae95'
down_revision: Union[str, None] = 'd96e0fff44bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sold_tours', sa.Column('buyer_id', sa.Integer(), nullable=False))
    op.add_column('sold_tours', sa.Column('seller_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sold_tours', 'users', ['buyer_id'], ['id'])
    op.create_foreign_key(None, 'sold_tours', 'users', ['seller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sold_tours', type_='foreignkey')
    op.drop_constraint(None, 'sold_tours', type_='foreignkey')
    op.drop_column('sold_tours', 'seller_id')
    op.drop_column('sold_tours', 'buyer_id')
    # ### end Alembic commands ###
