"""prices12

Revision ID: b43c077e3019
Revises: e75fceb49519
Create Date: 2023-09-07 12:21:49.278464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b43c077e3019'
down_revision: Union[str, None] = 'e75fceb49519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_prices', 'discount_percentage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_prices', sa.Column('discount_percentage', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
