"""prices

Revision ID: b59b78f440e4
Revises: eef619a712ee
Create Date: 2023-09-05 15:02:43.717784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b59b78f440e4'
down_revision: Union[str, None] = 'eef619a712ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_prices', sa.Column('discount_percentage', sa.Integer(), nullable=True))
    op.add_column('tour_prices', sa.Column('new_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_prices', 'new_price')
    op.drop_column('tour_prices', 'discount_percentage')
    # ### end Alembic commands ###
