"""statuses

Revision ID: b620b6b93d18
Revises: 5896bf53ee42
Create Date: 2023-08-26 00:30:44.228715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b620b6b93d18'
down_revision: Union[str, None] = '5896bf53ee42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('mailing_list', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mailing_list', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tours', sa.Column('v', sa.Integer(), nullable=True))
    op.add_column('tours', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tours', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'tours', 'tour_statuses', ['v'], ['id'])
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_constraint(None, 'tours', type_='foreignkey')
    op.drop_column('tours', 'updated_at')
    op.drop_column('tours', 'created_at')
    op.drop_column('tours', 'v')
    op.drop_column('mailing_list', 'updated_at')
    op.drop_column('mailing_list', 'created_at')
    op.drop_table('tour_statuses')
    # ### end Alembic commands ###
