"""views6

Revision ID: b62615dc7712
Revises: f1479cde766d
Create Date: 2023-09-05 10:01:20.872544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b62615dc7712'
down_revision: Union[str, None] = 'f1479cde766d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_tour_views', sa.Column('ip_addresses', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('ip_tour_views', sa.Column('tour_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ip_tour_views', 'tours', ['tour_id'], ['id'])
    op.drop_column('ip_tour_views', 'tour_ids')
    op.drop_column('ip_tour_views', 'ip_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_tour_views', sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('ip_tour_views', sa.Column('tour_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ip_tour_views', type_='foreignkey')
    op.drop_column('ip_tour_views', 'tour_id')
    op.drop_column('ip_tour_views', 'ip_addresses')
    # ### end Alembic commands ###
