"""region

Revision ID: b9436331571b
Revises: 238d8c29d63c
Create Date: 2023-09-04 14:24:11.441424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9436331571b'
down_revision: Union[str, None] = '238d8c29d63c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('region', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tours', 'region')
    # ### end Alembic commands ###
