"""prices13

Revision ID: cf1ca697f0fd
Revises: b43c077e3019
Create Date: 2023-09-07 12:24:45.754781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf1ca697f0fd'
down_revision: Union[str, None] = 'b43c077e3019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_prices', sa.Column('discount_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_prices', 'discount_percentage')
    # ### end Alembic commands ###
