"""accomm types

Revision ID: da05284517fe
Revises: 1e36d94d8ad2
Create Date: 2023-10-14 17:52:26.464258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da05284517fe'
down_revision: Union[str, None] = '1e36d94d8ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodation_types',
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accommodation_types_id'), 'accommodation_types', ['id'], unique=False)
    op.create_table('tour_accommodation_types',
    sa.Column('accommodation_type_id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['accommodation_type_id'], ['accommodation_types.id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_accommodation_types_id'), 'tour_accommodation_types', ['id'], unique=False)
    op.drop_column('tour_hotels', 'hotel_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_hotels', sa.Column('hotel_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tour_accommodation_types_id'), table_name='tour_accommodation_types')
    op.drop_table('tour_accommodation_types')
    op.drop_index(op.f('ix_accommodation_types_id'), table_name='accommodation_types')
    op.drop_table('accommodation_types')
    # ### end Alembic commands ###
