"""built

Revision ID: dbd08fd39e0a
Revises: 359469050ee9
Create Date: 2023-09-04 10:04:06.732280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd08fd39e0a'
down_revision: Union[str, None] = '359469050ee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('activities', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.add_column('currencies', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('currencies', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_currencies_id'), 'currencies', ['id'], unique=False)
    op.add_column('favorite_tours', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('favorite_tours', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('permissions', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('permissions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('role_permissions', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('role_permissions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('roles', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tour_activities', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tour_activities', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tour_activities_id'), 'tour_activities', ['id'], unique=False)
    op.create_index(op.f('ix_tour_comments_id'), 'tour_comments', ['id'], unique=False)
    op.add_column('tour_comments_media', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tour_comments_media', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tour_comments_media_id'), 'tour_comments_media', ['id'], unique=False)
    op.add_column('tour_prices', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tour_prices', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tour_prices_id'), 'tour_prices', ['id'], unique=False)
    op.add_column('tour_statuses', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tour_statuses', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('travelers_managers', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('travelers_managers', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travelers_managers', 'updated_at')
    op.drop_column('travelers_managers', 'created_at')
    op.drop_column('tour_statuses', 'updated_at')
    op.drop_column('tour_statuses', 'created_at')
    op.drop_index(op.f('ix_tour_prices_id'), table_name='tour_prices')
    op.drop_column('tour_prices', 'updated_at')
    op.drop_column('tour_prices', 'created_at')
    op.drop_index(op.f('ix_tour_comments_media_id'), table_name='tour_comments_media')
    op.drop_column('tour_comments_media', 'updated_at')
    op.drop_column('tour_comments_media', 'created_at')
    op.drop_index(op.f('ix_tour_comments_id'), table_name='tour_comments')
    op.drop_index(op.f('ix_tour_activities_id'), table_name='tour_activities')
    op.drop_column('tour_activities', 'updated_at')
    op.drop_column('tour_activities', 'created_at')
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'created_at')
    op.drop_column('role_permissions', 'updated_at')
    op.drop_column('role_permissions', 'created_at')
    op.drop_column('permissions', 'updated_at')
    op.drop_column('permissions', 'created_at')
    op.drop_column('favorite_tours', 'updated_at')
    op.drop_column('favorite_tours', 'created_at')
    op.drop_index(op.f('ix_currencies_id'), table_name='currencies')
    op.drop_column('currencies', 'updated_at')
    op.drop_column('currencies', 'created_at')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_column('activities', 'updated_at')
    op.drop_column('activities', 'created_at')
    # ### end Alembic commands ###
