"""updated tour days

Revision ID: dfc42a863cce
Revises: c3f4696b9062
Create Date: 2023-10-09 22:34:22.294402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfc42a863cce'
down_revision: Union[str, None] = 'c3f4696b9062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_days', sa.Column('region_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tour_days', 'regions', ['region_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tour_days', type_='foreignkey')
    op.drop_column('tour_days', 'region_id')
    # ### end Alembic commands ###
