"""5

Revision ID: e66eadde025c
Revises: 04ab484ad6e7
Create Date: 2023-08-14 15:46:05.637919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e66eadde025c'
down_revision: Union[str, None] = '04ab484ad6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travelers_managers',
    sa.Column('traveler_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['traveler_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('traveler_id', 'manager_id')
    )
    op.drop_table('traveler_managers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traveler_managers',
    sa.Column('traveler_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name='traveler_managers_manager_id_fkey'),
    sa.ForeignKeyConstraint(['traveler_id'], ['users.id'], name='traveler_managers_traveler_id_fkey')
    )
    op.drop_table('travelers_managers')
    # ### end Alembic commands ###
