"""prices11

Revision ID: e75fceb49519
Revises: a0ba9c01cd39
Create Date: 2023-09-07 12:17:50.040666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e75fceb49519'
down_revision: Union[str, None] = 'a0ba9c01cd39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_prices', sa.Column('new_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_prices', 'new_price')
    # ### end Alembic commands ###
