"""updated_tours

Revision ID: eaefe0067f9e
Revises: 20d278875849
Create Date: 2023-10-08 02:02:55.505245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaefe0067f9e'
down_revision: Union[str, None] = '20d278875849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('is_allowed_individually', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tours', 'is_allowed_individually')
    # ### end Alembic commands ###
