"""views5

Revision ID: f1479cde766d
Revises: 9dac530e6b60
Create Date: 2023-09-05 09:36:49.325567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1479cde766d'
down_revision: Union[str, None] = '9dac530e6b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_tour_views', sa.Column('tour_ids', sa.ARRAY(sa.Integer()), nullable=False))
    op.drop_constraint('ip_tour_views_tour_id_fkey', 'ip_tour_views', type_='foreignkey')
    op.drop_column('ip_tour_views', 'tour_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_tour_views', sa.Column('tour_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('ip_tour_views_tour_id_fkey', 'ip_tour_views', 'tours', ['tour_id'], ['id'])
    op.drop_column('ip_tour_views', 'tour_ids')
    # ### end Alembic commands ###
