"""travelermanagers id5

Revision ID: f2842bca1c18
Revises: b457af4ae3e5
Create Date: 2023-08-14 12:43:33.119997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2842bca1c18'
down_revision: Union[str, None] = 'b457af4ae3e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traveler_managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('traveler_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['traveler_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traveler_managers_id'), 'traveler_managers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traveler_managers_id'), table_name='traveler_managers')
    op.drop_table('traveler_managers')
    # ### end Alembic commands ###
