"""statuses3

Revision ID: f32b4fdd8844
Revises: 7b29b101c06b
Create Date: 2023-08-26 00:41:08.165419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f32b4fdd8844'
down_revision: Union[str, None] = '7b29b101c06b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tour_statuses_id'), 'tour_statuses', ['id'], unique=False)
    op.add_column('tours', sa.Column('status_id', sa.Integer(), nullable=False))
    op.drop_constraint('tours_v_fkey', 'tours', type_='foreignkey')
    op.create_foreign_key(None, 'tours', 'tour_statuses', ['status_id'], ['id'])
    op.drop_column('tours', 'v')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tours', type_='foreignkey')
    op.create_foreign_key('tours_v_fkey', 'tours', 'tour_statuses', ['v'], ['id'])
    op.drop_column('tours', 'status_id')
    op.drop_index(op.f('ix_tour_statuses_id'), table_name='tour_statuses')
    # ### end Alembic commands ###
