"""views10

Revision ID: f76751ec6ac2
Revises: 5e0ae690b323
Create Date: 2023-09-05 11:25:53.793438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f76751ec6ac2'
down_revision: Union[str, None] = '5e0ae690b323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_and_tours_views',
    sa.Column('ip_id', sa.Integer(), nullable=False),
    sa.Column('visited_times', sa.Integer(), nullable=True),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ip_id'], ['ip_tour_views.id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_and_tours_views_id'), 'ip_and_tours_views', ['id'], unique=False)
    op.add_column('ip_tour_views', sa.Column('ip_address', sa.String(), nullable=False))
    op.drop_constraint('ip_tour_views_tour_id_fkey', 'ip_tour_views', type_='foreignkey')
    op.drop_column('ip_tour_views', 'ip_addresses')
    op.drop_column('ip_tour_views', 'tour_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_tour_views', sa.Column('tour_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('ip_tour_views', sa.Column('ip_addresses', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.create_foreign_key('ip_tour_views_tour_id_fkey', 'ip_tour_views', 'tours', ['tour_id'], ['id'])
    op.drop_column('ip_tour_views', 'ip_address')
    op.drop_index(op.f('ix_ip_and_tours_views_id'), table_name='ip_and_tours_views')
    op.drop_table('ip_and_tours_views')
    # ### end Alembic commands ###
