"""updated_tours

Revision ID: f9f1509e663e
Revises: eaefe0067f9e
Create Date: 2023-10-08 10:17:05.239784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9f1509e663e'
down_revision: Union[str, None] = 'eaefe0067f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('included_in_price', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('tours', sa.Column('not_included_in_price', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tours', 'not_included_in_price')
    op.drop_column('tours', 'included_in_price')
    # ### end Alembic commands ###
